plugins:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - "db/schema.rb"
    - "db/migrate/**/*"
    - "bin/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Exclude:
    - "config/initializers/devise.rb"

RSpec/MultipleExpectations:
  Max: 3

RSpec/ExampleLength:
  Max: 10

Naming/VariableNumber:
  EnforcedStyle: normalcase